spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.104:3306/clinic-user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      host: 192.168.100.104
      port: 6379
      password: xgw18720322169.
      timeout: 10000
      database: 0
  mail:
    host: smtp.qq.com
    username: 2788456221@qq.com
    password: engtuytgmqugdfci
    default-encoding: utf-8
      # 其它参数
    properties:
      mail:
        smtp:
          # 如果是用SSL方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connection-timeout: 10000
          # 邮件发送时间的限制，单位毫秒
          write-timeout: 10000

